version: "2.4"
# For Texas Instruments
# The server profiles used in this example are intended for use with edge versions of the product image only.

services:
  pingdatagovernance:
    image: ${PING_IDENTITY_DEVOPS_REGISTRY}/pingdatagovernance:${PING_IDENTITY_DEVOPS_TAG}
    command: wait-for pingdirectory:389 -t 300 -- entrypoint.sh start-server
    environment:
      - SERVER_PROFILE_URL=https://github.com/toddbarrett-ping/pingidentity-server-profiles-for-ti.git
      - SERVER_PROFILE_PATH=pdg-pap-integration/pingdatagovernance
      - SERVER_PROFILE_PARENT=PDG
      - SERVER_PROFILE_PDG_URL=https://github.com/toddbarrett-ping/pingidentity-server-profiles-for-ti.git
      - SERVER_PROFILE_PDG_PATH=baseline/pingdatagovernance
    env_file:
      - ${HOME}/.pingidentity/devops
    ulimits:
      nproc:
        soft: 16384
        hard: 16384
      nofile:
        soft: 65535
        hard: 65535
    ports:
      - "8080:80"
      - "7443:443"
    networks:
      - pingnet-dmz
      - pingnet-internal
    volumes:
      - pingdatagovernance-out:/opt/out
    #  - ${HOME}/projects/devops/pingidentity-server-profiles/baseline/pingdatagovernance:/opt/in

  pingdatagovernancepap:
    image: ${PING_IDENTITY_DEVOPS_REGISTRY}/pingdatagovernancepap:${PING_IDENTITY_DEVOPS_TAG}
    # command: wait-for pingdirectory:389 -t 300 -- entrypoint.sh start-server
    environment:
      - SERVER_PROFILE_URL=https://github.com/toddbarrett-ping/pingidentity-server-profiles-for-ti.git
      - SERVER_PROFILE_PATH=pdg-pap-integration/pingdatagovernancepap
      - HTTPS_PORT=8443
      - PING_EXTERNAL_BASE_URL=ti.mypingdemo.com:8443
    env_file:
      - ${HOME}/.pingidentity/devops
    ulimits:
      nproc:
        soft: 16384
        hard: 16384
      nofile:
        soft: 65535
        hard: 65535
    ports:
      - "8443:8443"
    networks:
      - pingnet-dmz
    volumes:
      - pingdatagovernancepap-out:/opt/out
    #  - ${HOME}/projects/devops/pingidentity-server-profiles/pdg-pap-integration/pingdatagovernancepap:/opt/in

  pingdirectory:
    image: ${PING_IDENTITY_DEVOPS_REGISTRY}/pingdirectory:${PING_IDENTITY_DEVOPS_TAG}
    environment:
      - SERVER_PROFILE_URL=https://github.com/toddbarrett-ping/pingidentity-server-profiles-for-ti.git
      - SERVER_PROFILE_PATH=baseline/pingdirectory
    env_file:
      - ${HOME}/.pingidentity/devops
    ulimits:
      nproc:
        soft: 16384
        hard: 16384
      nofile:
        soft: 65535
        hard: 65535
    ports:
      - 1636-1646:636
      - 1443-1453:443
    networks:
      - pingnet-internal
    volumes:
      - pingdirectory-out:/opt/out
    #  - ${HOME}/projects/devops/pingidentity-server-profiles/baseline/pingdirectory:/opt/in

  pingdataconsole:
    image: ${PING_IDENTITY_DEVOPS_REGISTRY}/pingdataconsole:${PING_IDENTITY_DEVOPS_TAG}
    ports:
      - "9443:8443"
    networks:
      - pingnet-internal

networks:
    pingnet-internal:
    pingnet-dmz:

volumes:
  pingdatagovernance-out:
  pingdatagovernancepap-out:
  pingdirectory-out:
